# Generated by Django 5.2.8 on 2025-12-04 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('restaurant_address', models.TextField(max_length=255)),
                ('rest_phonenum', models.PositiveIntegerField()),
                ('rest_email', models.EmailField(max_length=100)),
                ('rating', models.FloatField()),
                ('category', models.CharField(choices=[('salad', 'Salad'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks'), ('shakes', 'Shakes'), ('desert', 'Desert'), ('ice-cream', 'Ice Cream')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('food_type', models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg')], default='veg', max_length=10)),
                ('restaurant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='swiggy.restaurant')),
            ],
        ),
    ]
