# Generated by Django 5.2.8 on 2025-12-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiggy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('salad', 'Salad'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks'), ('shakes', 'Shakes'), ('desert', 'Desert'), ('ice-cream', 'Ice Cream')], max_length=50),
        ),
    ]
